<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE TVSCHEDULE [
  <!ELEMENT TVSCHEDULE (CHANNEL+)>
  <!ELEMENT CHANNEL (BANNER,DAY+)>
  <!ELEMENT BANNER (#PCDATA)>
  <!ELEMENT DAY (DATE,(HOLIDAY|PROGRAMSLOT+)+)>
  <!ELEMENT HOLIDAY (#PCDATA)>
  <!ELEMENT DATE (#PCDATA)>
  <!ELEMENT PROGRAMSLOT (TIME,TITLE,DESCRIPTION?)>
  <!ELEMENT TIME (#PCDATA)>
  <!ELEMENT TITLE (#PCDATA)>
  <!ELEMENT DESCRIPTION (#PCDATA)>

  <!ATTLIST TVSCHEDULE NAME CDATA #REQUIRED>
  <!ATTLIST CHANNEL CHAN CDATA #REQUIRED>
  <!ATTLIST PROGRAMSLOT VTR CDATA #IMPLIED>
  <!ATTLIST TITLE RATING CDATA #IMPLIED>
  <!ATTLIST TITLE LANGUAGE CDATA #IMPLIED>

]>

<TVSCHEDULE NAME="适合幼儿园小朋友的">
  <CHANNEL CHAN="CCTV-2022">
    <BANNER>bAN BaN BAn</BANNER>
    <DAY>
      <DATE>周一</DATE>
      <HOLIDAY>呜呜</HOLIDAY>
      <HOLIDAY>嗯嗯</HOLIDAY>
      <PROGRAMSLOT VTR="啥呀">
        <TIME>8:50</TIME>
        <TITLE LANGUAGE="zh_CN" RATING="99%">哆啦A梦</TITLE>
        <DESCRIPTION>记忆面包</DESCRIPTION>
      </PROGRAMSLOT>
    </DAY>
  </CHANNEL>

  <CHANNEL CHAN="WWTV-1989">
    <BANNER>DOGE</BANNER>
    <DAY>
      <DATE>周五</DATE>
      <DATE>周五</DATE>
    </DAY>
  </CHANNEL>
</TVSCHEDULE>


